### ISSUE TITLE
无法连接互联网，求助！

### ISSUE THREAD

**Issue by Smilence-Maverick** [yeahwu/kinto#10]
多的不说了，直接上图吧。都是按照教程一步一步来的。

![Pic1](https://user-images.githubusercontent.com/55685347/91373789-cf83cf00-e849-11ea-9bc1-1e5b1f13a1cd.png)
![Pic2](https://user-images.githubusercontent.com/55685347/91373790-d01c6580-e849-11ea-8c56-5632d303809e.png)
![Pic3](https://user-images.githubusercontent.com/55685347/91373791-d0b4fc00-e849-11ea-90a5-88464975f5a3.png)
![Pic4](https://user-images.githubusercontent.com/55685347/91373785-ce52a200-e849-11ea-91f1-bdcc45f66740.png)

**Comment by yeahwu** [comment]
看你图，服务端和客户端配置都没问题。找客户端问题吧！

**Comment by Smilence-Maverick** [comment]
看来真是没有办法了，安卓：v2rayNG，Windows：v2rayN, Mac：V2rayU都试过了，都是最新的版本，问题依旧。。看来我是跟Kinto无缘了。
