### ISSUE TITLE
方法二修改了uuid和链接地址，deploy报错

### ISSUE THREAD

**Issue by zhifu1996** [yeahwu/kinto#12]
==> Your service has restarted with exit code 23
==> Please make sure your service kintohub is listening on port 8888
==> Note: you might also want to increase the deploy timeout if your service takes more than 60 seconds to start
==> Reason: Error

是超时间了吗

**Comment by yeahwu** [comment]
不要修改配置，默认部署一遍吧。看清教程

**Comment by zhifu1996** [comment]
默认还是能成功，亚洲能满速，谢谢
