### ISSUE TITLE
连接以后无法访问外网

### ISSUE THREAD

**Issue by isyume** [yeahwu/kinto#8]
按照教程一步一步走，全部都没有出现错误，使用的是最新的V2rayN-Core, 打开网站可以看到信息那里报错，已经更新本地Windows10时间：
`[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)`

**Comment by Smilence-Maverick** [comment]
类似的错误，同样的问题！等待解决方案~~是不是KintoHub给咔嚓了？？

**Comment by yeahwu** [comment]
服务端生成链接，显示Bad Request的话，服务端就没有问题。找客户端的问题，端口443，打开tls。

**Comment by isyume** [comment]
> 服务端生成链接，显示Bad Request的话，服务端就没有问题。找客户端的问题，端口443，打开tls。

地址没有https,端口443,加密方式none,传输协议ws，伪装类型none，底层传输安全tls，完全按照大佬read me上来的呢

**Comment by isyume** [comment]
问题我已经解决了，谢谢大佬此仓库。

**Comment by Smilence-Maverick** [comment]
> 问题我已经解决了，谢谢大佬此仓库。

咋解决的呢？
